/**'use client';

import { usePathname } from 'next/navigation';
import { Header } from '@/components/Header';
import { Navigation } from '@/components/Navigation';

export default function EmployeeLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const pathname = usePathname();
  const isLoginPage = pathname === '/employee/login';

  return (
    <div className="min-h-screen bg-gray-50">
      {!isLoginPage && <Header />}
      <div className={!isLoginPage ? "pt-16 pb-16 pl-0" : ""}>
        <div className="pl-0">
          {children}
        </div>
      </div>
      {!isLoginPage && <Navigation />}
      <style>{`
        main {
          padding-left: 0!important;
        }
      `}</style>
    </div>
  );
}*/
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}